spring:
  application:
    name: serverApi
server:
  port: 8886

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8899/eureka/
    #从服务端拉取服务注册信息的周期（秒）
    registry-fetch-interval-seconds: 10
  instance:
    #服务实例IP地址
    instance-id: serverApi
    #是否使用ip注册服务地址
    prefer-ip-address: false
    hostname: server
    ip-address: server
    #向server发送心跳的周期（秒）
    lease-renewal-interval-in-seconds: 5
    #超过多久没发送心跳就下线实例（秒）
    lease-expiration-duration-in-seconds: 15
